/* ordine:4*/
START TRANSACTION;
/*
tabella che contiene i menu giornalieri

*/
DROP TABLE IF EXISTS `menu_giornaliero`;

CREATE TABLE IF NOT EXISTS `menu_giornaliero` (
  `ID_MENU_SETTIMANALE` INTEGER NOT NULL,
  `GIORNO` INTEGER NOT NULL,
  `DATA_MENU` DATE,
  FOREIGN KEY fk_menu_settimanale(`ID_MENU_SETTIMANALE`) 
  REFERENCES menu_settimanale(`ID_MENU_SETTIMANALE`)
  ON DELETE CASCADE ON UPDATE CASCADE,

  PRIMARY KEY (`ID_MENU_SETTIMANALE`,`GIORNO`)
);

/*insert MENU_GIORNALIERO*/
INSERT INTO menu_giornaliero (ID_MENU_SETTIMANALE,GIORNO) VALUES(1,1);
INSERT INTO menu_giornaliero (ID_MENU_SETTIMANALE,GIORNO) VALUES(1,2);
INSERT INTO menu_giornaliero (ID_MENU_SETTIMANALE,GIORNO) VALUES(1,3);
INSERT INTO menu_giornaliero (ID_MENU_SETTIMANALE,GIORNO) VALUES(1,4);
INSERT INTO menu_giornaliero (ID_MENU_SETTIMANALE,GIORNO) VALUES(1,5);
INSERT INTO menu_giornaliero (ID_MENU_SETTIMANALE,GIORNO) VALUES(1,6);

INSERT INTO menu_giornaliero (ID_MENU_SETTIMANALE,GIORNO) VALUES(2,1);
INSERT INTO menu_giornaliero (ID_MENU_SETTIMANALE,GIORNO) VALUES(2,2);
INSERT INTO menu_giornaliero (ID_MENU_SETTIMANALE,GIORNO) VALUES(2,3);
INSERT INTO menu_giornaliero (ID_MENU_SETTIMANALE,GIORNO) VALUES(2,4);
INSERT INTO menu_giornaliero (ID_MENU_SETTIMANALE,GIORNO) VALUES(2,5);
INSERT INTO menu_giornaliero (ID_MENU_SETTIMANALE,GIORNO) VALUES(2,6);

COMMIT;
